// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: worldcup.proto

package worldcup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeTeam      string                 `protobuf:"bytes,1,opt,name=home_team,json=homeTeam,proto3" json:"home_team,omitempty"`
	AwayTeam      string                 `protobuf:"bytes,2,opt,name=away_team,json=awayTeam,proto3" json:"away_team,omitempty"`
	HomeGoals     int32                  `protobuf:"varint,3,opt,name=home_goals,json=homeGoals,proto3" json:"home_goals,omitempty"`
	AwayGoals     int32                  `protobuf:"varint,4,opt,name=away_goals,json=awayGoals,proto3" json:"away_goals,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictionRequest) Reset() {
	*x = PredictionRequest{}
	mi := &file_worldcup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionRequest) ProtoMessage() {}

func (x *PredictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldcup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionRequest.ProtoReflect.Descriptor instead.
func (*PredictionRequest) Descriptor() ([]byte, []int) {
	return file_worldcup_proto_rawDescGZIP(), []int{0}
}

func (x *PredictionRequest) GetHomeTeam() string {
	if x != nil {
		return x.HomeTeam
	}
	return ""
}

func (x *PredictionRequest) GetAwayTeam() string {
	if x != nil {
		return x.AwayTeam
	}
	return ""
}

func (x *PredictionRequest) GetHomeGoals() int32 {
	if x != nil {
		return x.HomeGoals
	}
	return 0
}

func (x *PredictionRequest) GetAwayGoals() int32 {
	if x != nil {
		return x.AwayGoals
	}
	return 0
}

func (x *PredictionRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PredictionRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type PredictionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictionResponse) Reset() {
	*x = PredictionResponse{}
	mi := &file_worldcup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionResponse) ProtoMessage() {}

func (x *PredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldcup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionResponse.ProtoReflect.Descriptor instead.
func (*PredictionResponse) Descriptor() ([]byte, []int) {
	return file_worldcup_proto_rawDescGZIP(), []int{1}
}

func (x *PredictionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PredictionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_worldcup_proto protoreflect.FileDescriptor

const file_worldcup_proto_rawDesc = "" +
	"\n" +
	"\x0eworldcup.proto\x12\bworldcup\"\xc5\x01\n" +
	"\x11PredictionRequest\x12\x1b\n" +
	"\thome_team\x18\x01 \x01(\tR\bhomeTeam\x12\x1b\n" +
	"\taway_team\x18\x02 \x01(\tR\bawayTeam\x12\x1d\n" +
	"\n" +
	"home_goals\x18\x03 \x01(\x05R\thomeGoals\x12\x1d\n" +
	"\n" +
	"away_goals\x18\x04 \x01(\x05R\tawayGoals\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"H\n" +
	"\x12PredictionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2`\n" +
	"\x11PredictionService\x12K\n" +
	"\x0eSendPrediction\x12\x1b.worldcup.PredictionRequest\x1a\x1c.worldcup.PredictionResponseB\fZ\n" +
	"./worldcupb\x06proto3"

var (
	file_worldcup_proto_rawDescOnce sync.Once
	file_worldcup_proto_rawDescData []byte
)

func file_worldcup_proto_rawDescGZIP() []byte {
	file_worldcup_proto_rawDescOnce.Do(func() {
		file_worldcup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worldcup_proto_rawDesc), len(file_worldcup_proto_rawDesc)))
	})
	return file_worldcup_proto_rawDescData
}

var file_worldcup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_worldcup_proto_goTypes = []any{
	(*PredictionRequest)(nil),  // 0: worldcup.PredictionRequest
	(*PredictionResponse)(nil), // 1: worldcup.PredictionResponse
}
var file_worldcup_proto_depIdxs = []int32{
	0, // 0: worldcup.PredictionService.SendPrediction:input_type -> worldcup.PredictionRequest
	1, // 1: worldcup.PredictionService.SendPrediction:output_type -> worldcup.PredictionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_worldcup_proto_init() }
func file_worldcup_proto_init() {
	if File_worldcup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worldcup_proto_rawDesc), len(file_worldcup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worldcup_proto_goTypes,
		DependencyIndexes: file_worldcup_proto_depIdxs,
		MessageInfos:      file_worldcup_proto_msgTypes,
	}.Build()
	File_worldcup_proto = out.File
	file_worldcup_proto_goTypes = nil
	file_worldcup_proto_depIdxs = nil
}
