apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment2
  namespace: sopes1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-deployment2
  template:
    metadata:
      labels:
        app: go-deployment2
    spec:
      containers:
      - name: grpc-server
        image: 34.59.122.115:5000/sopes1/go-deployment2:v1.0
        ports:
        - containerPort: 50051
        env:
        - name: GRPC_PORT
          value: "50051"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin123@rabbitmq.sopes1.svc.cluster.local:5672/"
        - name: CONTAINER_ROLE
          value: "grpc-server"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      - name: rabbitmq-writer
        image: 34.59.122.115:5000/sopes1/go-deployment2:v1.0
        ports:
        - containerPort: 50052
        env:
        - name: GRPC_PORT
          value: "50052"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin123@rabbitmq.sopes1.svc.cluster.local:5672/"
        - name: CONTAINER_ROLE
          value: "rabbitmq-writer"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "128Mi"