apiVersion: v1
kind: Service
metadata:
  name: go-deployment2-service
  namespace: sopes1
spec:
  selector:
    app: go-deployment2
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  type: ClusterIP